name: Python application 2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set python path initially
      run: |
        export PYTHONPATH=${PYTHONPATH}:./bvr/
    - name: Create Virtualenv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
    - name: Set python path inside virtualenv
      run: |
        export PYTHONPATH=${PYTHONPATH}:./bvr/
    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        source venv/bin/activate
        pip install pytest
        python -m pytest test/
